name: ${PROJECT}

services:
  php:
    image: snawden-php
    hostname: php
    env_file:
      - ./.env
    
    volumes:
      - ./data/www:/var/www/html
    
    ports:
      - "9000:9000"

  nginx:
    image: nginx:${NGINX_IMAGE}
    hostname: nginx
    environment:
      - PROJECT=${PROJECT}
      - TLD=${TLD}
    
    ports:
      - "80:80"
      - "443:443"
    
    
    
    volumes:
      # .template files are translated to .conf files with env vars replaced
      # ex.: ./nginx/templates/default.conf.template -> /etc/nginx/conf.d/default.conf
      - ./nginx/templates:/etc/nginx/templates
      - ./data/www:/var/www/html
      - ./logs:/var/log
      - ./ssl_cert:/ssl_cert

    # use localy only, while debugging
    # command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - php

  postgres:
    image: postgres:${POSTGRES_IMAGE}
    hostname: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_ROOT_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      - PGDATA=/var/lib/postgresql/data/PGDATA
    
    ports:
      - "5432:5432"
    
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata:rw

    depends_on:
      - php
      - nginx

volumes:
  postgres-data: